import { z } from 'zod';

/**
 * SDK build and release data.
 *
 * Shape is inherited from tidev/downloads-www `public/registry/`, generated by
 * tidev/titanium-builds-regen-action. Kept compatible on purpose: that data is
 * live today and this schema has to validate all 91 existing files.
 *
 * Schemas are permissive by default — `.loose()` lets the generator add fields
 * without breaking every consumer, and free-form strings are used where the
 * upstream values are messier than they look.
 */

/** ISO-8601. Not `z.iso.datetime()` — upstream has mixed precision and offsets. */
const IsoDate = z.string().min(1);

/**
 * Known values are `linux`, `osx`, `win32`, but this stays a string: a new
 * target should not invalidate the whole registry.
 */
export const AssetSchema = z
  .object({
    os: z.string(),
    size: z.number().int().nonnegative(),
    url: z.url(),
  })
  .loose();

/**
 * One build. Covers both GA/RC/Beta releases and CI branch builds — they differ
 * only in whether `expires` is present and where `url` points.
 *
 * `name` is the full build id (`13.4.0.GA`, `13.4.0.v20260728065841`);
 * `version` is the bare semver. No regex on either: real values include
 * `12.7.0.GA` and timestamped CI suffixes.
 */
export const BuildSchema = z
  .object({
    name: z.string().min(1),
    version: z.string().min(1),
    date: IsoDate,
    /**
     * Present on CI builds, absent on releases. Nullable because the generator
     * writes `null` when a run reports no artifact expiry.
     *
     * CI assets are nightly.link proxies to GitHub Actions artifacts, which die
     * after 90 days. Anything past this is a dead link — see TI-40.
     */
    expires: IsoDate.nullish(),
    /** Release tag page, or the Actions run for a CI build. */
    url: z.url(),
    assets: z.array(AssetSchema),
  })
  .loose();

export const BuildListSchema = z.array(BuildSchema);

/** `branches.json`: branch name to count of live (non-expired) builds. */
export const BranchesSchema = z.record(z.string(), z.number().int().nonnegative());

/**
 * `builds/pruned/<branch>.pruned.json` is **not** build data — it is a
 * negative-result cache.
 *
 * It records workflow runs whose artifacts no longer exist, so a regen skips
 * re-fetching artifact metadata for runs it already knows are dead. Tombstones
 * only; nothing here is meant for display. Both the directory and the suffix
 * say so, since an editor tab shows only the filename.
 */
export const PrunedRunSchema = z
  .object({
    id: z.number().int(),
    html_url: z.url(),
  })
  .loose();

export const PrunedListSchema = z.array(PrunedRunSchema);

export type Asset = z.infer<typeof AssetSchema>;
export type Build = z.infer<typeof BuildSchema>;
export type Branches = z.infer<typeof BranchesSchema>;
export type PrunedRun = z.infer<typeof PrunedRunSchema>;

/** Whether a build's artifacts are still downloadable. Releases never expire. */
export function isExpired(build: Build, now = Date.now()): boolean {
  if (!build.expires) {
    return false;
  }
  const at = Date.parse(build.expires);
  return Number.isFinite(at) && at <= now;
}
