import { contrast, hueDistance, oklchToHex } from './lib/oklch.ts';
/**
 * Generates the colour token block in src/app/globals.css.
 *
 * Everything about the palette lives in PALETTE below. To try a different
 * direction, change a hue or a chroma and re-run — do not hand-edit the
 * generated CSS, it will be overwritten.
 *
 *   pnpm tokens        regenerate
 *   pnpm check:contrast verify what came out
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

// ---------------------------------------------------------------- config

/**
 * Charcoal neutral with a steel-blue accent at the same hue — the accent is
 * the neutral with the volume turned up, rather than an unrelated colour.
 *
 * Blue also has the most room on the wheel: ~140° from danger and ~160° from
 * warning, so links never read as a warning or an error. Every warm accent we
 * tried had to negotiate for space between those two.
 */
const PALETTE = {
  neutral: { hue: 250, chroma: 0.014 },
  accent: { hue: 245, chroma: 0.15 },
  success: { hue: 150, chroma: 0.145 },
  warning: { hue: 85, chroma: 0.14 },
  danger: { hue: 25, chroma: 0.165 },
} as const;

/** Perceptual lightness per step. Shared by every ramp so they stay in sync. */
const LIGHTNESS: Record<number, number> = {
  50: 0.985,
  100: 0.955,
  200: 0.9,
  300: 0.82,
  400: 0.735,
  500: 0.64,
  600: 0.54,
  700: 0.455,
  800: 0.375,
  900: 0.305,
  950: 0.235,
};

const STEPS = Object.keys(LIGHTNESS)
  .map(Number)
  .sort((a, b) => a - b);

/**
 * Which ramp step each role uses, per theme. This is the other half of the
 * dial: if contrast is tight, move a role to a darker or lighter step rather
 * than reaching for a different hue.
 */
const ROLES = {
  light: {
    bg: '#FFFFFF',
    surface: ['neutral', 50],
    'surface-raised': '#FFFFFF',
    border: ['neutral', 200],
    'border-strong': ['neutral', 500],
    text: ['neutral', 950],
    'text-muted': ['neutral', 700],
    'text-subtle': ['neutral', 600],
    link: ['accent', 700],
    'link-hover': ['accent', 800],
    focus: ['accent', 600],
    success: ['success', 700],
    warning: ['warning', 700],
    danger: ['danger', 600],
    info: ['accent', 700],
    'logo-outer': ['neutral', 950],
    'logo-inner': ['neutral', 700],
  },
  dark: {
    bg: ['neutral', 950],
    surface: ['neutral', 900],
    'surface-raised': ['neutral', 800],
    border: ['neutral', 800],
    'border-strong': ['neutral', 600],
    text: ['neutral', 50],
    'text-muted': ['neutral', 300],
    'text-subtle': ['neutral', 400],
    link: ['accent', 300],
    'link-hover': ['accent', 200],
    focus: ['accent', 400],
    success: ['success', 300],
    warning: ['warning', 300],
    danger: ['danger', 300],
    info: ['accent', 300],
    // Tinted rather than plain white — the mark should read as part of the
    // system, not as a separate white element sitting on the page.
    'logo-outer': ['accent', 200],
    'logo-inner': ['accent', 400],
  },
} as const satisfies Record<string, Record<string, readonly [string, number] | string>>;

// ------------------------------------------------------------- generate

/** Chroma tapers toward both ends: near-white and near-black hold little colour. */
const chromaAt = (l: number, max: number) => max * (4 * l * (1 - l)) ** 0.65;

function buildRamp(hue: number, chroma: number): Record<number, string> {
  return Object.fromEntries(
    STEPS.map((s) => [s, oklchToHex(LIGHTNESS[s], chromaAt(LIGHTNESS[s], chroma), hue)])
  );
}

const ramps = Object.fromEntries(
  Object.entries(PALETTE).map(([name, { hue, chroma }]) => [name, buildRamp(hue, chroma)])
) as Record<keyof typeof PALETTE, Record<number, string>>;

const resolve = (theme: keyof typeof ROLES) =>
  Object.fromEntries(
    Object.entries(ROLES[theme]).map(([role, value]) => [
      role,
      typeof value === 'string' ? value : ramps[value[0] as keyof typeof PALETTE][value[1]],
    ])
  );

const light = resolve('light');
const dark = resolve('dark');

const roleBlock = (vars: Record<string, string>, indent: string, scheme: string) =>
  Object.entries(vars)
    .map(([k, v]) => `${indent}--${k}: ${v};`)
    .concat(`${indent}color-scheme: ${scheme};`)
    .join('\n');

const rampBlock = Object.entries(ramps)
  .map(([name, ramp]) => STEPS.map((s) => `  --color-${name}-${s}: ${ramp[s]};`).join('\n'))
  .join('\n\n');

const themeInline = Object.keys(light)
  .map((role) => `  --color-${role}: var(--${role});`)
  .join('\n');

const generated = `/* Generated by scripts/generate-tokens.ts — do not edit by hand.
   Change the PALETTE config there and re-run \`pnpm tokens\`. */

@theme {
${rampBlock}

  --font-sans: var(--font-plex-sans);
  --font-mono: var(--font-plex-mono);
}

/* Semantic roles. Components reference these, never a ramp step. */
:root {
${roleBlock(light, '  ', 'light')}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${roleBlock(dark, '    ', 'dark')}
  }
}

:root[data-theme="dark"] {
${roleBlock(dark, '  ', 'dark')}
}

@theme inline {
${themeInline}
}`;

// -------------------------------------------------------------- write

const cssPath = fileURLToPath(new URL('../src/app/globals.css', import.meta.url));
const START = '/* --- generated:tokens:start --- */';
const END = '/* --- generated:tokens:end --- */';

const css = readFileSync(cssPath, 'utf8');
const from = css.indexOf(START);
const to = css.indexOf(END);
if (from === -1 || to === -1) {
  console.error(`Missing ${START} / ${END} markers in globals.css`);
  process.exit(1);
}
writeFileSync(cssPath, css.slice(0, from + START.length) + '\n' + generated + '\n' + css.slice(to));

// ------------------------------------------------------------- report

console.log(`neutral ${PALETTE.neutral.hue}°  accent ${PALETTE.accent.hue}°`);
console.log(
  `accent separation — danger ${hueDistance(PALETTE.accent.hue, PALETTE.danger.hue).toFixed(0)}°, ` +
    `warning ${hueDistance(PALETTE.accent.hue, PALETTE.warning.hue).toFixed(0)}°, ` +
    `success ${hueDistance(PALETTE.accent.hue, PALETTE.success.hue).toFixed(0)}°\n`
);
for (const [theme, vars] of [
  ['light', light],
  ['dark', dark],
] as const) {
  console.log(theme);
  for (const role of [
    'text',
    'text-muted',
    'text-subtle',
    'link',
    'link-hover',
    'success',
    'warning',
    'danger',
  ]) {
    const onBg = contrast(vars[role], vars.bg);
    const onSurface = contrast(vars[role], vars.surface);
    const worst = Math.min(onBg, onSurface);
    const mark = worst >= 4.5 ? '  ' : '!!';
    console.log(
      `  ${mark} ${role.padEnd(12)} ${vars[role]}  bg ${onBg.toFixed(2)}  surface ${onSurface.toFixed(2)}`
    );
  }
}
