import { ApiIndexSchema, ApiTypeSchema } from '../src/lib/registry/index.ts';
import {
  assertAttributed,
  buildRedirects,
  inlineSites,
  unusedNamespaces,
  type Corpus,
  type LegacyPage,
} from './lib/legacy-api-map.ts';
import { API_DOCS_DIR } from './lib/registry-paths.ts';
/**
 * Builds the redirect map for the legacy titanium-docs `/api/*` URLs.
 *
 * The API reference is the most linked and most indexed part of the old site,
 * and every one of its URLs moves. Enumerating them by hand would miss some
 * quietly, so the map is generated from the old file tree and committed, then
 * read by next.config.ts at build time.
 *
 * Regenerate after an SDK docgen run that adds or renames types, or after
 * pulling titanium-docs. The output is sorted, so a regen that changes nothing
 * produces no diff.
 *
 *   node scripts/generate-api-redirects.ts <path-to-titanium-docs> [--check]
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

/** --check verifies the committed map is current without rewriting it. */
const checkOnly = process.argv.includes('--check');
const checkout = process.argv[2];
const root = fileURLToPath(new URL('..', import.meta.url));
const OUT = join(root, 'src/lib/docs/legacy-api-redirects.json');

if (!checkout || checkout.startsWith('--')) {
  console.error('usage: node scripts/generate-api-redirects.ts <path-to-titanium-docs> [--check]');
  console.error('  clone with: gh repo clone tidev/titanium-docs -- --depth=1');
  process.exit(2);
}

const apiDir = join(checkout, 'docs/api');
if (!existsSync(apiDir)) {
  console.error(`no docs/api/ under ${checkout} — is that a titanium-docs checkout?`);
  process.exit(2);
}

function walk(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) walk(full, out);
    else if (entry.name.endsWith('.md')) out.push(full);
  }
  return out;
}

/**
 * The heading, not the file name, is the canonical type.
 *
 * Old paths are lowercased and dot-flattened — `structs/apsconnectiondelegate.md`
 * is `APSConnectionDelegate` — so the casing cannot be recovered from the path,
 * and the new URLs are case-sensitive.
 */
const pages: LegacyPage[] = walk(apiDir)
  .map((file) => {
    const text = readFileSync(file, 'utf8');
    return {
      rel: relative(apiDir, file).split('\\').join('/'),
      name: text.match(/^#\s+(.+)$/m)?.[1]?.trim() ?? '',
      yml: (text.match(/^editUrl:\s*(\S+)/m)?.[1] ?? '').split('/apidoc/')[1] ?? '',
      // A directory beside the page is what made VuePress treat it as a section
      // header, which is the only reason the old sidebar links it without the
      // extension. See `legacyUrls`.
      section: existsSync(file.replace(/\.md$/, '')),
    };
  })
  .sort((a, b) => a.rel.localeCompare(b.rel));

const nameless = pages.filter((p) => !p.name);
if (nameless.length) {
  console.error(`no heading in: ${nameless.map((p) => p.rel).join(', ')}`);
  process.exit(1);
}

/**
 * The map is checked against `main`, the mutable tree compiled from the SDK's
 * default branch. It is the only complete corpus — a released version predates
 * types added since — and this is a name lookup, not a claim about which
 * version a reader lands on.
 */
const sdkDir = join(root, API_DOCS_DIR, 'main');
const index = ApiIndexSchema.parse(JSON.parse(readFileSync(join(sdkDir, 'index.json'), 'utf8')));
const types = readdirSync(join(sdkDir, 'types'))
  .filter((f) => f.endsWith('.json'))
  .map((f) => ApiTypeSchema.parse(JSON.parse(readFileSync(join(sdkDir, 'types', f), 'utf8'))));

const corpus: Corpus = {
  types: new Set(index.types.map((t) => t.name)),
  inlined: inlineSites(types, new Set(index.inlined)),
};

const map = buildRedirects(pages, corpus);
assertAttributed(pages, corpus, map);

const stale = unusedNamespaces(pages);
if (stale.length) {
  console.error(`MODULE_IDS names namespaces the old tree does not have: ${stale.join(', ')}`);
  process.exit(1);
}

/**
 * No commit hash or timestamp in the output: the map is a pure function of the
 * old tree and the compiled corpus, so a regen that changes neither must
 * produce no diff. That is what makes `--check` meaningful in CI.
 */
const payload = {
  $comment: 'Generated by scripts/generate-api-redirects.ts — do not edit by hand.',
  source: { repo: 'tidev/titanium-docs', pages: pages.length },
  sdk: map.sdk,
  modules: map.modules,
  unresolved: map.unresolved,
};
const json = `${JSON.stringify(payload, null, 2)}\n`;

const total = map.sdk.length + map.modules.length;
console.log(`${pages.length} pages -> ${total} redirects`);
console.log(`  ${map.sdk.length} to /docs/sdk/, ${map.modules.length} to /modules/`);
console.log(`  ${map.sdk.filter((r) => r.destination.includes('#')).length} carry a member anchor`);
if (map.unresolved.length) {
  console.log(`  ${map.unresolved.length} land on the reference index:`);
  for (const source of map.unresolved) console.log(`    ${source}`);
}

if (checkOnly) {
  const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
  if (current === json) {
    console.log('Committed map is current.');
  } else {
    console.error('Committed map is stale — rerun without --check.');
    process.exit(1);
  }
} else {
  writeFileSync(OUT, json);
  console.log(`Wrote ${relative(root, OUT)}`);
}
